FROM node:14-alpine AS base

ENV NODE_ENV build

WORKDIR /app

# Dependencies installation
COPY . /app
RUN npm ci \
    && npm run build \
    && npm prune --production

# -------------------------

FROM node:14-alpine

ENV NODE_ENV build

WORKDIR /app

COPY --from=base /app/package*.json /app/
COPY --from=base /app/node_modules/ /app/node_modules/
COPY --from=base /app/dist/ /app/dist/

ENV PORT 8080
EXPOSE 8080

CMD ["node", "dist/main"]